#trigger:
#  - main

stages:
  - stage: Build
    jobs:
      - job: BuildWebApp
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: ArchiveFiles@2
            displayName: "Archive Files"
            inputs:
              rootFolderOrFile: "$(build.sourcesDirectory)"
              includeRootFolder: false
          - task: PublishBuildArtifacts@1
            displayName: "Publish Build Artifacts"
            condition: succeededOrFailed()

  - stage: Dev
    jobs:
      - job: Deploy
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: "current"
              downloadType: "single"
              artifactName: "drop"
              downloadPath: "$(System.DefaultWorkingDirectory)"
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: "AzureRM"
              azureSubscription: "absServiceConnection" 
              appType: 'webApp'
              WebAppName: 'mzinbookstore-linux'
              packageForLinux:  "$(System.DefaultWorkingDirectory)/**/*.zip"

      - job: Test
        dependsOn: Deploy
        pool:
          vmImage: ubuntu-latest
        steps:
          - template: steps_test.yml
            parameters:
              url: "https://mzinbookstore-linux.azurewebsites.net"
              browser: "chrome"
